project_name: smaf825
release:
  github:
    owner: but80
    name: smaf825
brew:
  github:
    owner: but80
    name: homebrew-tap
builds:
- goos:
#  - linux
  - darwin
  - windows
  goarch:
  - amd64
  main: .
  ldflags: -s -w -X main.version={{.Version}}
  binary: smaf825
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}'
  files:
  - LICENSE*
  - README*
