// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/smaf.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VM35FMVoiceVersion int32

const (
	VM35FMVoiceVersion_VM3LIB       VM35FMVoiceVersion = 0
	VM35FMVoiceVersion_VM3EXCLUSIVE VM35FMVoiceVersion = 1
	VM35FMVoiceVersion_VM5          VM35FMVoiceVersion = 2
)

var VM35FMVoiceVersion_name = map[int32]string{
	0: "VM3LIB",
	1: "VM3EXCLUSIVE",
	2: "VM5",
}
var VM35FMVoiceVersion_value = map[string]int32{
	"VM3LIB":       0,
	"VM3EXCLUSIVE": 1,
	"VM5":          2,
}

func (x VM35FMVoiceVersion) String() string {
	return proto.EnumName(VM35FMVoiceVersion_name, int32(x))
}
func (VM35FMVoiceVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_smaf_2abcb595a9430170, []int{0}
}

type VoiceType int32

const (
	VoiceType_FM  VoiceType = 0
	VoiceType_PCM VoiceType = 1
	VoiceType_AL  VoiceType = 2
)

var VoiceType_name = map[int32]string{
	0: "FM",
	1: "PCM",
	2: "AL",
}
var VoiceType_value = map[string]int32{
	"FM":  0,
	"PCM": 1,
	"AL":  2,
}

func (x VoiceType) String() string {
	return proto.EnumName(VoiceType_name, int32(x))
}
func (VoiceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_smaf_2abcb595a9430170, []int{1}
}

type VM5VoiceLib struct {
	Programs             []*VM35VoicePC `protobuf:"bytes,1,rep,name=programs" json:"programs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *VM5VoiceLib) Reset()         { *m = VM5VoiceLib{} }
func (m *VM5VoiceLib) String() string { return proto.CompactTextString(m) }
func (*VM5VoiceLib) ProtoMessage()    {}
func (*VM5VoiceLib) Descriptor() ([]byte, []int) {
	return fileDescriptor_smaf_2abcb595a9430170, []int{0}
}
func (m *VM5VoiceLib) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VM5VoiceLib.Unmarshal(m, b)
}
func (m *VM5VoiceLib) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VM5VoiceLib.Marshal(b, m, deterministic)
}
func (dst *VM5VoiceLib) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VM5VoiceLib.Merge(dst, src)
}
func (m *VM5VoiceLib) XXX_Size() int {
	return xxx_messageInfo_VM5VoiceLib.Size(m)
}
func (m *VM5VoiceLib) XXX_DiscardUnknown() {
	xxx_messageInfo_VM5VoiceLib.DiscardUnknown(m)
}

var xxx_messageInfo_VM5VoiceLib proto.InternalMessageInfo

func (m *VM5VoiceLib) GetPrograms() []*VM35VoicePC {
	if m != nil {
		return m.Programs
	}
	return nil
}

type VM35VoicePC struct {
	Version              VM35FMVoiceVersion `protobuf:"varint,1,opt,name=version,enum=pb.VM35FMVoiceVersion" json:"version,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	BankMsb              uint32             `protobuf:"varint,3,opt,name=bank_msb,json=bankMsb" json:"bank_msb,omitempty"`
	BankLsb              uint32             `protobuf:"varint,4,opt,name=bank_lsb,json=bankLsb" json:"bank_lsb,omitempty"`
	Pc                   uint32             `protobuf:"varint,5,opt,name=pc" json:"pc,omitempty"`
	DrumNote             uint32             `protobuf:"varint,6,opt,name=drum_note,json=drumNote" json:"drum_note,omitempty"`
	VoiceType            VoiceType          `protobuf:"varint,7,opt,name=voice_type,json=voiceType,enum=pb.VoiceType" json:"voice_type,omitempty"`
	FmVoice              *VM35FMVoice       `protobuf:"bytes,8,opt,name=fm_voice,json=fmVoice" json:"fm_voice,omitempty"`
	PcmVoice             *VM35PCMVoice      `protobuf:"bytes,9,opt,name=pcm_voice,json=pcmVoice" json:"pcm_voice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VM35VoicePC) Reset()         { *m = VM35VoicePC{} }
func (m *VM35VoicePC) String() string { return proto.CompactTextString(m) }
func (*VM35VoicePC) ProtoMessage()    {}
func (*VM35VoicePC) Descriptor() ([]byte, []int) {
	return fileDescriptor_smaf_2abcb595a9430170, []int{1}
}
func (m *VM35VoicePC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VM35VoicePC.Unmarshal(m, b)
}
func (m *VM35VoicePC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VM35VoicePC.Marshal(b, m, deterministic)
}
func (dst *VM35VoicePC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VM35VoicePC.Merge(dst, src)
}
func (m *VM35VoicePC) XXX_Size() int {
	return xxx_messageInfo_VM35VoicePC.Size(m)
}
func (m *VM35VoicePC) XXX_DiscardUnknown() {
	xxx_messageInfo_VM35VoicePC.DiscardUnknown(m)
}

var xxx_messageInfo_VM35VoicePC proto.InternalMessageInfo

func (m *VM35VoicePC) GetVersion() VM35FMVoiceVersion {
	if m != nil {
		return m.Version
	}
	return VM35FMVoiceVersion_VM3LIB
}

func (m *VM35VoicePC) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VM35VoicePC) GetBankMsb() uint32 {
	if m != nil {
		return m.BankMsb
	}
	return 0
}

func (m *VM35VoicePC) GetBankLsb() uint32 {
	if m != nil {
		return m.BankLsb
	}
	return 0
}

func (m *VM35VoicePC) GetPc() uint32 {
	if m != nil {
		return m.Pc
	}
	return 0
}

func (m *VM35VoicePC) GetDrumNote() uint32 {
	if m != nil {
		return m.DrumNote
	}
	return 0
}

func (m *VM35VoicePC) GetVoiceType() VoiceType {
	if m != nil {
		return m.VoiceType
	}
	return VoiceType_FM
}

func (m *VM35VoicePC) GetFmVoice() *VM35FMVoice {
	if m != nil {
		return m.FmVoice
	}
	return nil
}

func (m *VM35VoicePC) GetPcmVoice() *VM35PCMVoice {
	if m != nil {
		return m.PcmVoice
	}
	return nil
}

type VM35FMVoice struct {
	DrumKey              uint32            `protobuf:"varint,1,opt,name=drum_key,json=drumKey" json:"drum_key,omitempty"`
	Panpot               uint32            `protobuf:"varint,2,opt,name=panpot" json:"panpot,omitempty"`
	Bo                   uint32            `protobuf:"varint,3,opt,name=bo" json:"bo,omitempty"`
	Lfo                  uint32            `protobuf:"varint,4,opt,name=lfo" json:"lfo,omitempty"`
	Pe                   bool              `protobuf:"varint,5,opt,name=pe" json:"pe,omitempty"`
	Alg                  uint32            `protobuf:"varint,6,opt,name=alg" json:"alg,omitempty"`
	Operators            []*VM35FMOperator `protobuf:"bytes,7,rep,name=operators" json:"operators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VM35FMVoice) Reset()         { *m = VM35FMVoice{} }
func (m *VM35FMVoice) String() string { return proto.CompactTextString(m) }
func (*VM35FMVoice) ProtoMessage()    {}
func (*VM35FMVoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_smaf_2abcb595a9430170, []int{2}
}
func (m *VM35FMVoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VM35FMVoice.Unmarshal(m, b)
}
func (m *VM35FMVoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VM35FMVoice.Marshal(b, m, deterministic)
}
func (dst *VM35FMVoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VM35FMVoice.Merge(dst, src)
}
func (m *VM35FMVoice) XXX_Size() int {
	return xxx_messageInfo_VM35FMVoice.Size(m)
}
func (m *VM35FMVoice) XXX_DiscardUnknown() {
	xxx_messageInfo_VM35FMVoice.DiscardUnknown(m)
}

var xxx_messageInfo_VM35FMVoice proto.InternalMessageInfo

func (m *VM35FMVoice) GetDrumKey() uint32 {
	if m != nil {
		return m.DrumKey
	}
	return 0
}

func (m *VM35FMVoice) GetPanpot() uint32 {
	if m != nil {
		return m.Panpot
	}
	return 0
}

func (m *VM35FMVoice) GetBo() uint32 {
	if m != nil {
		return m.Bo
	}
	return 0
}

func (m *VM35FMVoice) GetLfo() uint32 {
	if m != nil {
		return m.Lfo
	}
	return 0
}

func (m *VM35FMVoice) GetPe() bool {
	if m != nil {
		return m.Pe
	}
	return false
}

func (m *VM35FMVoice) GetAlg() uint32 {
	if m != nil {
		return m.Alg
	}
	return 0
}

func (m *VM35FMVoice) GetOperators() []*VM35FMOperator {
	if m != nil {
		return m.Operators
	}
	return nil
}

type VM35FMOperator struct {
	Multi                uint32   `protobuf:"varint,1,opt,name=multi" json:"multi,omitempty"`
	Dt                   uint32   `protobuf:"varint,2,opt,name=dt" json:"dt,omitempty"`
	Ar                   uint32   `protobuf:"varint,3,opt,name=ar" json:"ar,omitempty"`
	Dr                   uint32   `protobuf:"varint,4,opt,name=dr" json:"dr,omitempty"`
	Sr                   uint32   `protobuf:"varint,5,opt,name=sr" json:"sr,omitempty"`
	Rr                   uint32   `protobuf:"varint,6,opt,name=rr" json:"rr,omitempty"`
	Sl                   uint32   `protobuf:"varint,7,opt,name=sl" json:"sl,omitempty"`
	Tl                   uint32   `protobuf:"varint,8,opt,name=tl" json:"tl,omitempty"`
	Ksl                  uint32   `protobuf:"varint,9,opt,name=ksl" json:"ksl,omitempty"`
	Dam                  uint32   `protobuf:"varint,10,opt,name=dam" json:"dam,omitempty"`
	Dvb                  uint32   `protobuf:"varint,11,opt,name=dvb" json:"dvb,omitempty"`
	Fb                   uint32   `protobuf:"varint,12,opt,name=fb" json:"fb,omitempty"`
	Ws                   uint32   `protobuf:"varint,13,opt,name=ws" json:"ws,omitempty"`
	Xof                  bool     `protobuf:"varint,14,opt,name=xof" json:"xof,omitempty"`
	Sus                  bool     `protobuf:"varint,15,opt,name=sus" json:"sus,omitempty"`
	Ksr                  bool     `protobuf:"varint,16,opt,name=ksr" json:"ksr,omitempty"`
	Eam                  bool     `protobuf:"varint,17,opt,name=eam" json:"eam,omitempty"`
	Evb                  bool     `protobuf:"varint,18,opt,name=evb" json:"evb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VM35FMOperator) Reset()         { *m = VM35FMOperator{} }
func (m *VM35FMOperator) String() string { return proto.CompactTextString(m) }
func (*VM35FMOperator) ProtoMessage()    {}
func (*VM35FMOperator) Descriptor() ([]byte, []int) {
	return fileDescriptor_smaf_2abcb595a9430170, []int{3}
}
func (m *VM35FMOperator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VM35FMOperator.Unmarshal(m, b)
}
func (m *VM35FMOperator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VM35FMOperator.Marshal(b, m, deterministic)
}
func (dst *VM35FMOperator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VM35FMOperator.Merge(dst, src)
}
func (m *VM35FMOperator) XXX_Size() int {
	return xxx_messageInfo_VM35FMOperator.Size(m)
}
func (m *VM35FMOperator) XXX_DiscardUnknown() {
	xxx_messageInfo_VM35FMOperator.DiscardUnknown(m)
}

var xxx_messageInfo_VM35FMOperator proto.InternalMessageInfo

func (m *VM35FMOperator) GetMulti() uint32 {
	if m != nil {
		return m.Multi
	}
	return 0
}

func (m *VM35FMOperator) GetDt() uint32 {
	if m != nil {
		return m.Dt
	}
	return 0
}

func (m *VM35FMOperator) GetAr() uint32 {
	if m != nil {
		return m.Ar
	}
	return 0
}

func (m *VM35FMOperator) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *VM35FMOperator) GetSr() uint32 {
	if m != nil {
		return m.Sr
	}
	return 0
}

func (m *VM35FMOperator) GetRr() uint32 {
	if m != nil {
		return m.Rr
	}
	return 0
}

func (m *VM35FMOperator) GetSl() uint32 {
	if m != nil {
		return m.Sl
	}
	return 0
}

func (m *VM35FMOperator) GetTl() uint32 {
	if m != nil {
		return m.Tl
	}
	return 0
}

func (m *VM35FMOperator) GetKsl() uint32 {
	if m != nil {
		return m.Ksl
	}
	return 0
}

func (m *VM35FMOperator) GetDam() uint32 {
	if m != nil {
		return m.Dam
	}
	return 0
}

func (m *VM35FMOperator) GetDvb() uint32 {
	if m != nil {
		return m.Dvb
	}
	return 0
}

func (m *VM35FMOperator) GetFb() uint32 {
	if m != nil {
		return m.Fb
	}
	return 0
}

func (m *VM35FMOperator) GetWs() uint32 {
	if m != nil {
		return m.Ws
	}
	return 0
}

func (m *VM35FMOperator) GetXof() bool {
	if m != nil {
		return m.Xof
	}
	return false
}

func (m *VM35FMOperator) GetSus() bool {
	if m != nil {
		return m.Sus
	}
	return false
}

func (m *VM35FMOperator) GetKsr() bool {
	if m != nil {
		return m.Ksr
	}
	return false
}

func (m *VM35FMOperator) GetEam() bool {
	if m != nil {
		return m.Eam
	}
	return false
}

func (m *VM35FMOperator) GetEvb() bool {
	if m != nil {
		return m.Evb
	}
	return false
}

type VM35PCMVoice struct {
	RawData              []byte   `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VM35PCMVoice) Reset()         { *m = VM35PCMVoice{} }
func (m *VM35PCMVoice) String() string { return proto.CompactTextString(m) }
func (*VM35PCMVoice) ProtoMessage()    {}
func (*VM35PCMVoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_smaf_2abcb595a9430170, []int{4}
}
func (m *VM35PCMVoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VM35PCMVoice.Unmarshal(m, b)
}
func (m *VM35PCMVoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VM35PCMVoice.Marshal(b, m, deterministic)
}
func (dst *VM35PCMVoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VM35PCMVoice.Merge(dst, src)
}
func (m *VM35PCMVoice) XXX_Size() int {
	return xxx_messageInfo_VM35PCMVoice.Size(m)
}
func (m *VM35PCMVoice) XXX_DiscardUnknown() {
	xxx_messageInfo_VM35PCMVoice.DiscardUnknown(m)
}

var xxx_messageInfo_VM35PCMVoice proto.InternalMessageInfo

func (m *VM35PCMVoice) GetRawData() []byte {
	if m != nil {
		return m.RawData
	}
	return nil
}

func init() {
	proto.RegisterType((*VM5VoiceLib)(nil), "pb.VM5VoiceLib")
	proto.RegisterType((*VM35VoicePC)(nil), "pb.VM35VoicePC")
	proto.RegisterType((*VM35FMVoice)(nil), "pb.VM35FMVoice")
	proto.RegisterType((*VM35FMOperator)(nil), "pb.VM35FMOperator")
	proto.RegisterType((*VM35PCMVoice)(nil), "pb.VM35PCMVoice")
	proto.RegisterEnum("pb.VM35FMVoiceVersion", VM35FMVoiceVersion_name, VM35FMVoiceVersion_value)
	proto.RegisterEnum("pb.VoiceType", VoiceType_name, VoiceType_value)
}

func init() { proto.RegisterFile("pb/smaf.proto", fileDescriptor_smaf_2abcb595a9430170) }

var fileDescriptor_smaf_2abcb595a9430170 = []byte{
	// 608 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x54, 0x4f, 0x6f, 0xd3, 0x3c,
	0x1c, 0x5e, 0xdc, 0xad, 0x49, 0xbc, 0xa5, 0xcb, 0x6b, 0xbd, 0x9a, 0x8c, 0xb8, 0x54, 0x15, 0x87,
	0x32, 0x60, 0x4c, 0x9b, 0x76, 0x81, 0x13, 0x94, 0x4d, 0x9a, 0x68, 0x60, 0x0a, 0x10, 0x71, 0xab,
	0xec, 0xc6, 0x99, 0xaa, 0x26, 0xb5, 0x65, 0xa7, 0x29, 0xfd, 0x62, 0x5c, 0xb9, 0xf1, 0xb9, 0x90,
	0x7f, 0x4e, 0xba, 0x21, 0x6e, 0xbf, 0xe7, 0x4f, 0xec, 0xc7, 0x8f, 0xdd, 0xe2, 0x48, 0xf1, 0xd7,
	0xa6, 0x62, 0xc5, 0x99, 0xd2, 0xb2, 0x96, 0x04, 0x29, 0x3e, 0x7a, 0x83, 0x0f, 0xb3, 0xe4, 0x2a,
	0x93, 0x8b, 0xb9, 0x98, 0x2e, 0x38, 0x79, 0x81, 0x03, 0xa5, 0xe5, 0xbd, 0x66, 0x95, 0xa1, 0xde,
	0xb0, 0x37, 0x3e, 0xbc, 0x38, 0x3e, 0x53, 0xfc, 0x2c, 0x4b, 0x2e, 0x9d, 0xe7, 0x6e, 0x92, 0xee,
	0x0c, 0xa3, 0x5f, 0xc8, 0x7e, 0xbc, 0x53, 0xc8, 0x39, 0xf6, 0x1b, 0xa1, 0xcd, 0x42, 0xae, 0xa8,
	0x37, 0xf4, 0xc6, 0x83, 0x8b, 0x93, 0xee, 0xdb, 0x9b, 0x04, 0x3c, 0x99, 0x53, 0xd3, 0xce, 0x46,
	0x08, 0xde, 0x5f, 0xb1, 0x4a, 0x50, 0x34, 0xf4, 0xc6, 0x61, 0x0a, 0x33, 0x79, 0x82, 0x03, 0xce,
	0x56, 0xcb, 0x59, 0x65, 0x38, 0xed, 0x0d, 0xbd, 0x71, 0x94, 0xfa, 0x16, 0x27, 0x86, 0xef, 0xa4,
	0xd2, 0x70, 0xba, 0xff, 0x20, 0x4d, 0x0d, 0x27, 0x03, 0x8c, 0xd4, 0x9c, 0x1e, 0x00, 0x89, 0xd4,
	0x9c, 0x3c, 0xc5, 0x61, 0xae, 0xd7, 0xd5, 0x6c, 0x25, 0x6b, 0x41, 0xfb, 0x40, 0x07, 0x96, 0xf8,
	0x24, 0x6b, 0x41, 0x5e, 0x62, 0xdc, 0xd8, 0x3c, 0xb3, 0x7a, 0xab, 0x04, 0xf5, 0x21, 0x6b, 0x04,
	0x59, 0x2d, 0xfb, 0x75, 0xab, 0x44, 0x1a, 0x36, 0xdd, 0x48, 0x4e, 0x71, 0x50, 0x54, 0x33, 0xc0,
	0x34, 0x18, 0x7a, 0x8f, 0x3b, 0x69, 0xcf, 0x95, 0xfa, 0x45, 0x05, 0x03, 0x79, 0x85, 0x43, 0x35,
	0xef, 0xcc, 0x21, 0x98, 0xe3, 0xce, 0x7c, 0x37, 0x69, 0xdd, 0x81, 0x9a, 0x3b, 0xfb, 0xe8, 0xa7,
	0xe7, 0x1a, 0x6c, 0xd7, 0xb1, 0x07, 0x84, 0xd4, 0x4b, 0xb1, 0x85, 0x0a, 0xa3, 0xd4, 0xb7, 0xf8,
	0xa3, 0xd8, 0x92, 0x13, 0xdc, 0x57, 0x6c, 0xa5, 0x64, 0x0d, 0x65, 0x45, 0x69, 0x8b, 0xec, 0xc1,
	0xb9, 0x6c, 0x8b, 0x42, 0x5c, 0x92, 0x18, 0xf7, 0xca, 0x42, 0xb6, 0xf5, 0xd8, 0x11, 0xaa, 0x11,
	0x50, 0x4d, 0x90, 0x22, 0x25, 0xac, 0x83, 0x95, 0xf7, 0x6d, 0x29, 0x76, 0x24, 0xe7, 0x38, 0x94,
	0x4a, 0x68, 0x56, 0x4b, 0x6d, 0xa8, 0x0f, 0xd7, 0x4e, 0x1e, 0x8e, 0xf8, 0xb9, 0x95, 0xd2, 0x07,
	0xd3, 0xe8, 0x37, 0xc2, 0x83, 0xbf, 0x55, 0xf2, 0x3f, 0x3e, 0xa8, 0xd6, 0x65, 0xbd, 0x68, 0x83,
	0x3b, 0x60, 0x37, 0xcf, 0xbb, 0xc8, 0x28, 0x87, 0xb8, 0x4c, 0x77, 0x71, 0x99, 0x06, 0x5d, 0xb7,
	0x69, 0x51, 0x0e, 0xd8, 0xe8, 0xee, 0x1e, 0x0d, 0x60, 0xad, 0xdb, 0xac, 0x48, 0x3b, 0xbd, 0x84,
	0x2b, 0xb3, 0x7a, 0x69, 0x71, 0x5d, 0xc2, 0xb5, 0x44, 0x29, 0xaa, 0x4b, 0x7b, 0xb8, 0xa5, 0x29,
	0xa1, 0xfa, 0x28, 0xb5, 0xa3, 0x65, 0x72, 0x56, 0x51, 0xec, 0x98, 0x9c, 0x55, 0xc0, 0x34, 0x9c,
	0x1e, 0xb6, 0x4c, 0x03, 0xaf, 0xa7, 0xe0, 0xf4, 0xc8, 0xad, 0x52, 0x00, 0xde, 0x18, 0x1a, 0x39,
	0xbc, 0x31, 0xf6, 0x8b, 0x1f, 0xb2, 0xa0, 0x03, 0xe8, 0xd0, 0x8e, 0x96, 0x31, 0x6b, 0x43, 0x8f,
	0x1d, 0x63, 0xd6, 0xc6, 0xed, 0xac, 0x69, 0xec, 0x98, 0xa5, 0xd1, 0x96, 0x11, 0xac, 0xa2, 0xff,
	0x39, 0x46, 0xb8, 0x9d, 0x45, 0xc3, 0x29, 0x69, 0x99, 0x86, 0x8f, 0x9e, 0xe3, 0xa3, 0xc7, 0x6f,
	0xc3, 0xbe, 0x00, 0xcd, 0x36, 0xb3, 0x9c, 0xd5, 0x0c, 0x8a, 0x3c, 0x4a, 0x7d, 0xcd, 0x36, 0x1f,
	0x58, 0xcd, 0x4e, 0xdf, 0x62, 0xf2, 0xef, 0x6f, 0x89, 0x60, 0xdc, 0xcf, 0x92, 0xcb, 0xe9, 0xed,
	0xfb, 0x78, 0x8f, 0xc4, 0xb0, 0xd8, 0xf5, 0xf7, 0xc9, 0xf4, 0xdb, 0x97, 0xdb, 0xec, 0x3a, 0xf6,
	0x88, 0x8f, 0x7b, 0x59, 0x72, 0x15, 0xa3, 0xd3, 0x67, 0x38, 0xdc, 0x3d, 0x6e, 0xd2, 0xc7, 0xe8,
	0x26, 0x89, 0xf7, 0xac, 0x7a, 0x37, 0x49, 0x62, 0xcf, 0x12, 0xef, 0xa6, 0x31, 0xe2, 0x7d, 0xf8,
	0x63, 0xb8, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x3f, 0xcc, 0x2c, 0x29, 0x04, 0x00, 0x00,
}
